choose_channels:  
  - 3  
  - 4  
  - 5
channels: 3
n_nodes: 1
c_date: 5
dilation: 1
emb_dim: 8
dropout: 0.3
kernel_size: 3
order: 2

sta_layers: 1
use_update: False
share: False
time_emb: False

read_path: "601058.xlsx"
save_path: "model_save/601058_12_12.pt" #{name_blocks_code_step}
excel_path: "pred.xlsx"
inp_len: 12
pred_len: 12

current_timestamp_str: '2024-10-21 13:15'

epoches: 50
device: "cuda"
lr: 1.0e-3
weight_decay: 1.0e-3
batch_size: 32
train_size: 0.99
val_size: 0.01